# Generated by Django 4.2.11 on 2024-04-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_covidvaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
