# Generated by Django 4.2.11 on 2024-04-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_alter_admin_status_alter_patient_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='dob',
        ),
    ]
